name: "xinux-manager-infra"

services:
  # elastic:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
  #   restart: always
  #   volumes:
  #     - elastic:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  postgres:
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis:7.4
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379

volumes:
  elastic:
  postgres:
  redis:
